services:
  mongodb:
    image: mongo:8
    container_name: identity-mongodb
    hostname: mongodb

    restart: unless-stopped

    ports:
      - '27017:27017'

    command:
      - mongod
      - --bind_ip_all
      - --replSet
      - rs0

    volumes:
      - identity_mongodb_data:/data/db

volumes:
  identity_mongodb_data:
